### ISSUE TITLE
Improper Sinon version in package.json

### ISSUE THREAD

**Issue by fredck** [benderjs/benderjs-sinon#5]
Package.json is set to load Sinon "^1.10.3". This will take minor releases above "10". Right now, it installed Sinon 1.12.2, which is not compatible with my environment (because I have RequireJS as well).

The version should be corrected to "~1.10.3".

**Comment by gregpabian** [comment]
> The version should be corrected to "~1.10.3".

Or could be updated to the latest Sinon.js version, but then we need an adapter that will load it using Require.js and defer the test execution...

**Comment by fredck** [comment]
True... in fact I've opened #6 for this.
