### ISSUE TITLE
Create adapter to allow the newest Sinon in a RequireJS environment

### ISSUE THREAD

**Issue by fredck** [benderjs/benderjs-sinon#6]
The newest Sinon had the great idea of defining itself as an anonymous module if define is available. This breaks in a bender environment containing RequireJS because Sinon is included with `<script>`.

An adapter is require so it is loaded with AMD is define is available or with `<script>` otherwise.

Additionally, I would open an issue at Sinon's side for this as well.

**Comment by gregpabian** [comment]
There's already an issue for it - cjohansen/Sinon.JS#639

**Comment by fredck** [comment]
> There's already an issue for it - cjohansen/Sinon.JS#639

That's not exactly the error I was having.

In my case, it throw an error because Sinon tried to define an anonymous module while the script is loaded with `<script>` not with `require()`.

**Comment by gregpabian** [comment]
True, my bad :)

**Comment by gregpabian** [comment]
I tried to implement an adapter for the latest Sinon.js today, but I'm still unable to publish it because of the problems with the build version trying to define an anonymous module. Hopefully this PR - cjohansen/Sinon.JS#679 - will solve that problem and we'll be able to publish the update.

**Comment by Reinmar** [comment]
Fixed by #7.
